language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - TARGET_API=29
    - BUILD_TOOLS=29.0.3

android:
  components:
    - tools # https://github.com/travis-ci/travis-ci/issues/5049
    - tools # https://github.com/travis-ci/travis-ci/issues/6040
    - android-$TARGET_API
    - platform-tools
    - build-tools-$BUILD_TOOLS
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-x86_64-android-$TARGET_API
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-$TARGET_API --abi x86_64 -c 100M -no-accel -gpu on
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew jacocoTestReport connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
